const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,10);
const clone=x=>JSON.parse(JSON.stringify(x));
const dateKey=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const addDays=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d};
const MEALS=[['breakfast','Frühstück','☀️'],['lunch','Mittagessen','🍽️'],['dinner','Abendessen','🌙']];
const UNITS=['g','kg','ml','l','Stück'];
const UNIT_GROUP={g:'mass',kg:'mass',ml:'volume',l:'volume','Stück':'count'};
const UNIT_FACTOR={g:1,kg:1000,ml:1,l:1000,'Stück':1};
const CHEF_PROXY='https://mealmate-chefkoch.grxq8hqb8r.workers.dev';

const seed={
 recipes:[
  {id:'r1',title:'Cremige Tomatenpasta',emoji:'🍝',image:'',time:25,servings:2,tags:['Vegetarisch','Schnell'],ingredients:['250 g Pasta','1 Dose gehackte Tomaten','1 Zwiebel','2 Knoblauchzehen','100 ml Sahne','Parmesan','Salz','Pfeffer'],steps:['Pasta al dente kochen.','Zwiebel und Knoblauch anschwitzen.','Tomaten und Sahne zugeben und 10 Minuten köcheln.','Pasta unterheben und mit Parmesan servieren.'],nutrition:{kcal:640,protein:21,carbs:91},favorite:true,rating:0,cookedCount:0,lastCooked:null,source:null},
  {id:'r2',title:'Kartoffel-Gemüse-Pfanne',emoji:'🥔',image:'',time:35,servings:2,tags:['Vegetarisch','Meal Prep'],ingredients:['500 g Kartoffeln','1 Paprika','1 Zucchini','1 Zwiebel','2 EL Öl','Paprikapulver','Salz','Pfeffer'],steps:['Kartoffeln würfeln und vorkochen.','Gemüse schneiden.','Alles in der Pfanne goldbraun braten und würzen.'],nutrition:{kcal:470,protein:10,carbs:68},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:null},
  {id:'r3',title:'Hähnchen-Reis-Bowl',emoji:'🍚',image:'',time:30,servings:2,tags:['Proteinreich'],ingredients:['300 g Hähnchenbrust','180 g Reis','1 Gurke','1 Karotte','2 EL Sojasauce','1 TL Honig'],steps:['Reis kochen.','Hähnchen anbraten und mit Sojasauce und Honig glasieren.','Gemüse schneiden und alles in Bowls anrichten.'],nutrition:{kcal:590,protein:43,carbs:72},favorite:true,rating:0,cookedCount:0,lastCooked:null,source:null},
  {id:'r4',title:'Pfannkuchen',emoji:'🥞',image:'',time:20,servings:2,tags:['Süß','Schnell'],ingredients:['200 g Mehl','2 Eier','350 ml Milch','1 Prise Salz','1 TL Vanilleextrakt','Öl zum Braten'],steps:['Zutaten zu einem glatten Teig verrühren.','10 Minuten ruhen lassen.','Portionsweise in wenig Öl ausbacken.'],nutrition:{kcal:520,protein:20,carbs:65},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:null}
 ],
 pantry:[
  {id:'p1',name:'Pasta',quantity:250,unit:'g'},
  {id:'p2',name:'gehackte Tomaten',quantity:1,unit:'Stück'},
  {id:'p3',name:'Zwiebel',quantity:2,unit:'Stück'},
  {id:'p4',name:'Knoblauchzehen',quantity:4,unit:'Stück'},
  {id:'p5',name:'Kartoffeln',quantity:500,unit:'g'},
  {id:'p6',name:'Milch',quantity:250,unit:'ml'}
 ],
 shopping:[],planner:{},settings:{name:'Felix'},taste:{ratings:0}
};

function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function safeUrl(u=''){try{const x=new URL(u);return ['http:','https:','data:'].includes(x.protocol)?u:''}catch{return u.startsWith('data:image/')?u:''}}
function normalizeUnit(u=''){const x=String(u).trim().toLowerCase().replace('.','');if(x==='kg')return 'kg';if(x==='g'||x==='gr')return 'g';if(x==='ml')return 'ml';if(x==='l'||x==='liter')return 'l';if(['stück','stk','st','stueck'].includes(x))return 'Stück';return ''}
function unitGroup(u){return UNIT_GROUP[normalizeUnit(u)]||''}
function toBase(q,u){const n=Number(q);u=normalizeUnit(u);return Number.isFinite(n)&&UNIT_FACTOR[u]?n*UNIT_FACTOR[u]:0}
function fromBase(v,u){u=normalizeUnit(u);return UNIT_FACTOR[u]?v/UNIT_FACTOR[u]:v}
function niceNumber(n){if(!Number.isFinite(+n))return '0';const x=Math.round((+n)*100)/100;return new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(x)}
function formatQty(q,u){return `${niceNumber(q)} ${u||''}`.trim()}
function canonicalName(s=''){return String(s).toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[.,;:]/g,' ').replace(/\b(dose|dosen|packung|packungen|prise|prisen|el|tl)\b/g,' ').replace(/\s+/g,' ').trim().replace(/(en|e|n|s)$/,'')}
function nameMatches(a,b){const x=canonicalName(a),y=canonicalName(b);return !!x&&!!y&&(x===y||x.includes(y)||y.includes(x))}
function parseNumber(v){const s=String(v||'').trim().replace(',','.');if(/^\d+\/\d+$/.test(s)){const [a,b]=s.split('/').map(Number);return b?a/b:0}const n=Number(s);return Number.isFinite(n)?n:0}
function parseIngredient(text=''){
 const raw=String(text).trim();
 let m=raw.match(/^\s*(\d+(?:[.,]\d+)?|\d+\/\d+)\s*(kg|g|gr\.?|ml|l|liter|stück|stk\.?|st\.?|stueck)\s+(.+)$/i);
 if(m)return {name:m[3].trim(),quantity:parseNumber(m[1]),unit:normalizeUnit(m[2]),raw,quantified:true};
 m=raw.match(/^\s*(\d+(?:[.,]\d+)?|\d+\/\d+)\s+(.+)$/i);
 if(m&&!/^(el|tl|prise[n]?|dose[n]?|packung(?:en)?|becher|tasse[n]?)\b/i.test(m[2]))return {name:m[2].trim(),quantity:parseNumber(m[1]),unit:'Stück',raw,quantified:true};
 return {name:raw.replace(/^\s*(\d+(?:[.,]\d+)?|\d+\/\d+)\s*/,'').trim()||raw,quantity:null,unit:'',raw,quantified:false};
}
function pantryBase(name,group){return data.pantry.filter(p=>nameMatches(p.name,name)&&unitGroup(p.unit)===group).reduce((sum,p)=>sum+toBase(p.quantity,p.unit),0)}
function ingredientAvailability(text){const ing=parseIngredient(text);if(!ing.quantified){const found=data.pantry.some(p=>nameMatches(p.name,ing.name)&&Number(p.quantity)>0);return {fraction:found?1:0,ing,available:null}}
 const g=unitGroup(ing.unit),need=toBase(ing.quantity,ing.unit),have=pantryBase(ing.name,g);return {fraction:need?Math.min(1,have/need):0,ing,available:fromBase(have,ing.unit)}
}
function matchRecipe(r){if(!r.ingredients.length)return 0;const score=r.ingredients.reduce((s,i)=>s+ingredientAvailability(i).fraction,0);return Math.round(score/r.ingredients.length*100)}
function cover(r,detail=false){const u=safeUrl(r.image||'');return u?`<div class="${detail?'detail-cover':'recipe-cover'} has-image" style="background-image:url('${esc(u)}')"><span>${r.emoji||'🍽️'}</span></div>`:`<div class="${detail?'detail-cover':'recipe-cover'}"><span>${r.emoji||'🍽️'}</span></div>`}
function emptyMealPlan(){return {breakfast:null,lunch:null,dinner:null}}
function normalizePantryItem(p){if(typeof p==='string'){const x=parseIngredient(p);return {id:uid(),name:x.name||p,quantity:x.quantity||1,unit:x.unit||'Stück'}}return {id:p.id||uid(),name:p.name||p.text||'Zutat',quantity:Number(p.quantity)||0,unit:normalizeUnit(p.unit)||'Stück'}}
function normalizeShoppingItem(x){if(typeof x==='string')x={text:x};if(x.text&&!x.name){const p=parseIngredient(x.text);x={...x,name:p.name,quantity:p.quantity||1,unit:p.unit||'Stück'}}const unit=normalizeUnit(x.unit)||'Stück',quantity=Number(x.quantity)||0;return {id:x.id||uid(),name:x.name||'Artikel',quantity,unit,done:!!x.done,requiredBase:Number(x.requiredBase)||toBase(Number(x.requiredQuantity)||quantity,unit),availableBase:Number(x.availableBase)||0,source:x.source||'manuell'}}
function migrate(d){d=d||clone(seed);d.recipes=d.recipes||[];d.recipes.forEach(r=>{r.image??='';r.rating??=0;r.cookedCount??=0;r.lastCooked??=null;r.source??=null;r.tags??=[];r.ingredients??=[];r.steps??=[]});d.taste??={ratings:0};d.settings??={name:'Felix'};d.settings.chefProxy=CHEF_PROXY;d.pantry=(d.pantry||[]).map(normalizePantryItem);d.shopping=(d.shopping||[]).map(normalizeShoppingItem);const old=d.planner||{};d.planner={};Object.entries(old).forEach(([k,v])=>{d.planner[k]=typeof v==='string'?{breakfast:null,lunch:v,dinner:null}:{...emptyMealPlan(),...(v||{})}});return d}
const store={get(){try{const raw=localStorage.getItem('mealmate_data');return migrate(raw?JSON.parse(raw):clone(seed))}catch{return migrate(clone(seed))}},set(v){localStorage.setItem('mealmate_data',JSON.stringify(v))}};
let data=store.get(),view='home',filter='Alle',search='',modal=null,toast='';
let chefFeed=[],chefQuery='Schnelle Gerichte',chefLoading=false,chefError='';
function save(){store.set(data);render()}
function flash(msg){toast=msg;render();setTimeout(()=>{toast='';render()},2600)}
function nav(){return `<nav class="nav">${[['home','⌂','Start'],['discover','✦','Entdecken'],['recipes','◫','Rezepte'],['plan','◷','Plan'],['shopping','✓','Einkauf'],['pantry','◉','Vorrat']].map(([v,i,l])=>`<button data-nav="${v}" class="${view===v?'active':''}"><span class="ico">${i}</span>${l}</button>`).join('')}</nav>`}
function header(title='MealMate',sub='Deine private Koch-App'){return `<header class="top"><div class="brandrow"><div><div class="brand">${title}</div><div class="sub">${sub}</div></div><button class="iconbtn" data-action="settings">⚙︎</button></div></header>`}
function recipeCard(r){const m=matchRecipe(r);return `<article class="card" data-recipe="${r.id}">${cover(r)}<div class="recipe-body"><div class="recipe-title">${esc(r.title)}</div><div class="meta"><span class="pill">${r.time||'–'} Min.</span><span class="pill ${m>=60?'ok':''}">${m}% da</span>${r.rating?`<span class="pill">★ ${r.rating}/5</span>`:''}</div></div></article>`}
function preferenceSummary(){const rated=data.recipes.filter(r=>r.rating>0);if(!rated.length)return 'Bewerte Gerichte nach dem Kochen – daraus lernt MealMate deinen Geschmack.';const tags={};rated.forEach(r=>r.tags.forEach(t=>tags[t]=(tags[t]||0)+(r.rating-3)));const top=Object.entries(tags).sort((a,b)=>b[1]-a[1]).filter(x=>x[1]>0).slice(0,2).map(x=>x[0]);return top.length?`Du magst bisher besonders: ${top.join(' · ')}.`:'MealMate lernt weiter aus deinen Bewertungen, Favoriten und gekochten Gerichten.'}
function scoreRecipe(r,used=[]){let s=matchRecipe(r)*.035+(r.favorite?2.2:0)+(r.rating||0)*1.5+Math.min(r.cookedCount||0,3)*.15;const tagAffinity={};data.recipes.filter(x=>x.rating).forEach(x=>x.tags.forEach(t=>tagAffinity[t]=(tagAffinity[t]||0)+(x.rating-3)));r.tags.forEach(t=>s+=(tagAffinity[t]||0)*.35);if(r.time<=30)s+=.4;if(r.lastCooked){const days=(Date.now()-new Date(r.lastCooked))/86400000;if(days<5)s-=4;else if(days<10)s-=1.5}if(used.some(x=>x?.tags?.some(t=>r.tags.includes(t))))s-=.7;return s+Math.random()*.15}
function suggestedRecipe(meal,used){const usage={};used.forEach(r=>{if(r)usage[r.id]=(usage[r.id]||0)+1});const candidates=[...data.recipes];candidates.sort((a,b)=>{const bonus=r=>meal==='breakfast'?(r.tags.includes('Süß')||/pfannkuchen|müsli|brot|ei|joghurt/i.test(r.title)?3:-1):(r.tags.includes('Süß')?-1:1);return (scoreRecipe(b,used)+bonus(b)-(usage[b.id]||0)*1.8)-(scoreRecipe(a,used)+bonus(a)-(usage[a.id]||0)*1.8)});return candidates[0]||null}
function suggestWeek(){const used=[];for(let i=0;i<7;i++){const k=dateKey(addDays(i));data.planner[k]=emptyMealPlan();for(const [meal] of MEALS){const r=suggestedRecipe(meal,used);if(r){data.planner[k][meal]=r.id;used.push(r)}}}save()}
function home(){const possible=[...data.recipes].sort((a,b)=>scoreRecipe(b)-scoreRecipe(a)).slice(0,4);return `${header()}<main class="content"><section class="hero"><h1>Was kann ich essen?</h1><p>Ich gleiche Vorräte und Geschmack ab und werde mit jeder Bewertung persönlicher.</p></section><div class="learn-card"><b>MealMate lernt mit</b><span>${esc(preferenceSummary())}</span></div><div class="search"><input id="globalSearch" placeholder="Rezepte durchsuchen…" value="${esc(search)}"></div><div class="section-title"><h2>Für dich empfohlen</h2><button data-action="suggestWeek">Woche planen</button></div><div class="grid">${possible.map(recipeCard).join('')}</div><div class="section-title"><h2>Favoriten</h2><button data-nav="recipes">Alle</button></div><div class="grid">${data.recipes.filter(r=>r.favorite).slice(0,3).map(recipeCard).join('')||'<div class="empty">Noch keine Favoriten.</div>'}</div></main><button class="fab" data-action="addRecipe">+</button>${nav()}`}
function chefFeedCard(x){return `<article class="chef-feed-card"><div class="chef-feed-image ${x.image?'has-image':''}" ${x.image?`style="background-image:url('${esc(safeUrl(x.image))}')"`:''}><span>${x.image?'':'🍲'}</span><div class="chef-badge">Chefkoch</div></div><div class="chef-feed-body"><h3>${esc(x.title)}</h3>${x.meta?`<p>${esc(x.meta)}</p>`:''}<div class="chef-feed-actions"><button class="secondary" data-chef-save="${esc(x.url)}">♡ Merken</button><button class="secondary" data-chef-plan="${esc(x.url)}">+ Plan</button><a href="${esc(x.url)}" target="_blank" rel="noopener">Original ↗</a></div></div></article>`}
function discover(){const qs=['Schnelle Gerichte','Lasagne','Hähnchen','Pasta','Kartoffeln','Vegetarisch','Auflauf','Pfannkuchen'],proxyReady=!!normalizeProxy(CHEF_PROXY);return `${header('Entdecken','Chefkoch direkt durchscrollen')}<main class="content discover-content"><section class="hero discover-hero"><h1>Chefkoch entdecken</h1><p>Scrolle direkt in MealMate durch Rezeptvorschläge. Interessante Gerichte kannst du merken oder direkt in deinen Wochenplan übernehmen.</p></section>${!proxyReady?`<div class="notice proxy-notice"><b>Einmalige Einrichtung nötig</b><br>Damit Chefkoch den Abruf auf dem iPhone nicht blockiert, braucht MealMate deinen kostenlosen Cloudflare-Worker.<br><button class="secondary topgap" data-action="settings">Worker-Adresse eintragen</button></div>`:''}<form id="chefFeedSearch" class="search chef-feed-search"><input name="q" id="chefSearch" placeholder="z. B. Lasagne, Hähnchen, schnell…" value="${esc(chefQuery)}"><button class="primary" ${proxyReady?'':'disabled'}>Suchen</button></form><div class="chips wrap">${qs.map(q=>`<button class="chip ${chefQuery===q?'active':''}" data-chef-feed="${esc(q)}" ${proxyReady?'':'disabled'}>${esc(q)}</button>`).join('')}</div><div class="section-title"><h2>Rezepte</h2><button data-action="reloadChefFeed" ${proxyReady?'':'disabled'}>↻ Neu laden</button></div>${!proxyReady?'<div class="chef-loader">Nach der Worker-Einrichtung erscheinen hier die Chefkoch-Rezepte.</div>':chefLoading?'<div class="chef-loader">Chefkoch-Rezepte werden geladen …</div>':chefError?`<div class="notice">${esc(chefError)}<br><button class="secondary topgap" data-action="openChefSearch">Suche bei Chefkoch öffnen ↗</button></div>`:`<div class="chef-feed">${chefFeed.map(chefFeedCard).join('')||'<div class="chef-loader">Feed wird vorbereitet …</div>'}</div>`}<div class="notice">Die Rezeptdetails bleiben bei Chefkoch. „Merken“ importiert die strukturierten Rezeptdaten in deine private MealMate-Sammlung, soweit Chefkoch sie technisch bereitstellt.</div><div class="section-title"><h2>Deine persönlichen Empfehlungen</h2></div><div class="grid">${[...data.recipes].sort((a,b)=>scoreRecipe(b)-scoreRecipe(a)).slice(0,3).map(recipeCard).join('')}</div></main>${nav()}`}

function recipes(){const tags=['Alle','Favoriten','Schnell','Vegetarisch','Proteinreich','Meal Prep'];const list=data.recipes.filter(r=>{const q=search.toLowerCase(),qok=!q||r.title.toLowerCase().includes(q)||r.ingredients.join(' ').toLowerCase().includes(q),fok=filter==='Alle'||(filter==='Favoriten'?r.favorite:r.tags.includes(filter));return qok&&fok});return `${header('Rezepte',`${data.recipes.length} gespeichert`)}<main class="content"><div class="search"><input id="globalSearch" placeholder="Suche nach Rezept oder Zutat…" value="${esc(search)}"></div><div class="chips">${tags.map(t=>`<button class="chip ${filter===t?'active':''}" data-filter="${t}">${t}</button>`).join('')}</div><div class="section-title"><h2>Deine Rezepte</h2><button data-action="importRecipe">Importieren</button></div><div class="grid">${list.map(recipeCard).join('')||'<div class="empty">Keine Treffer.</div>'}</div></main><button class="fab" data-action="addRecipe">+</button>${nav()}`}
function mealSlot(k,meal,label,icon){const rid=data.planner[k]?.[meal],r=data.recipes.find(x=>x.id===rid);return `<div class="meal-slot ${r?'filled':''}" data-plan="${k}" data-meal="${meal}" role="button" tabindex="0" ${r?'draggable="true"':''}><span class="meal-icon">${icon}</span><span class="meal-copy"><small>${label}</small>${r?`<b>${esc(r.title)}</b><em>${matchRecipe(r)}% Vorrat · ${r.time} Min.</em>`:`<b>Gericht auswählen</b><em>Antippen zum Planen</em>`}</span>${r?`<span class="drag-handle" data-drag-handle aria-label="Gericht verschieben" title="Ziehen zum Verschieben">⠿</span>`:`<span class="chev">›</span>`}</div>`}
function plan(){const days=[0,1,2,3,4,5,6].map(addDays);return `${header('Wochenplan','Frühstück, Mittag- und Abendessen')}<main class="content"><button class="primary suggest" data-action="suggestWeek">✦ Ganze Woche automatisch vorschlagen</button><div class="learn-card"><b>21 Mahlzeiten im Blick</b><span>MealMate berücksichtigt Geschmack, Vorräte, Kochhistorie und Abwechslung.</span></div><div class="week-list">${days.map(d=>{const k=dateKey(d);data.planner[k]??=emptyMealPlan();return `<section class="day-card"><div class="day-head"><div><b>${d.toLocaleDateString('de-DE',{weekday:'long'})}</b><span>${d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}</span></div></div>${MEALS.map(([meal,label,icon])=>mealSlot(k,meal,label,icon)).join('')}</section>`}).join('')}</div><div class="section-title"><h2>Einkauf automatisch ergänzen</h2></div><button class="primary full" data-action="planToShopping">Benötigte Zutaten abzüglich Vorrat hinzufügen</button></main>${nav()}`}
function unitOptions(selected='Stück'){return UNITS.map(u=>`<option ${u===selected?'selected':''}>${u}</option>`).join('')}
function addForm(id,placeholder,buttonLabel='+'){return `<form id="${id}" class="amount-form"><input name="name" placeholder="${placeholder}" required><input name="quantity" type="number" inputmode="decimal" min="0.01" step="0.01" value="1" required><select name="unit">${unitOptions('Stück')}</select><button class="primary">${buttonLabel}</button></form>`}
function shoppingRow(x){const req=fromBase(x.requiredBase,x.unit),avail=Math.min(fromBase(x.availableBase,x.unit),req);return `<div class="row shopping-row"><button class="check ${x.done?'done':''}" data-check="${x.id}">${x.done?'✓':''}</button><div class="row-main"><div class="row-title ${x.done?'struck':''}">${esc(x.name)}</div><div class="amount-main">${formatQty(x.quantity,x.unit)} <span>kaufen</span></div><div class="row-sub">Benötigt ${formatQty(req,x.unit)} · vorhanden ${formatQty(avail,x.unit)}</div></div>${x.done?`<button class="secondary mini-wide" data-stock-shopping="${x.id}">→ Vorrat</button>`:''}<button class="iconbtn mini" data-del-shopping="${x.id}">×</button></div>`}
function shopping(){const buy=data.shopping.filter(x=>x.quantity>0.0001),covered=data.shopping.filter(x=>x.quantity<=0.0001);return `${header('Einkaufsliste','Vorrat wird automatisch gegengerechnet')}<main class="content">${addForm('shoppingForm','Artikel, z. B. Milch')}<div class="list">${buy.map(shoppingRow).join('')||'<div class="empty">Aktuell musst du nichts einkaufen.</div>'}</div>${covered.length?`<details class="covered"><summary>${covered.length} durch Vorrat abgedeckt</summary><div class="covered-list">${covered.map(x=>`<div class="covered-item"><span>✓ ${esc(x.name)}</span><small>${formatQty(fromBase(x.requiredBase,x.unit),x.unit)} benötigt · genug vorhanden</small><button data-del-shopping="${x.id}">×</button></div>`).join('')}</div></details>`:''}${data.shopping.some(x=>x.done)?'<button class="secondary danger full topgap" data-action="clearDone">Erledigte löschen</button>':''}</main>${nav()}`}
function pantryRow(p){return `<div class="row"><div class="stock-dot">◉</div><div class="row-main"><div class="row-title">${esc(p.name)}</div><div class="amount-main">${formatQty(p.quantity,p.unit)} <span>vorhanden</span></div></div><button class="secondary mini-wide" data-edit-pantry="${p.id}">Ändern</button><button class="iconbtn mini" data-del-pantry="${p.id}">×</button></div>`}
function pantry(){return `${header('Vorrat','Mengen statt nur Produktnamen')}<main class="content">${addForm('pantryForm','Zutat, z. B. Milch')}<div class="list">${data.pantry.map(pantryRow).join('')||'<div class="empty">Noch keine Vorräte eingetragen.</div>'}</div><div class="section-title"><h2>Passt zu deinem Vorrat</h2></div><div class="grid">${[...data.recipes].sort((a,b)=>matchRecipe(b)-matchRecipe(a)).slice(0,6).map(recipeCard).join('')}</div></main>${nav()}`}
function stars(r){return `<div class="rating"><span>Wie hat es dir geschmeckt?</span><div>${[1,2,3,4,5].map(n=>`<button data-rate="${n}" data-id="${r.id}" class="${r.rating>=n?'on':''}">★</button>`).join('')}</div><small>${r.rating?`Deine Bewertung: ${r.rating}/5`:'Deine Bewertung verbessert künftige Vorschläge.'}</small></div>`}
function ingredientLine(text){const a=ingredientAvailability(text),i=a.ing;if(!i.quantified)return `<li><span>${esc(text)}</span><small class="ingredient-stock ${a.fraction?'oktxt':''}">${a.fraction?'vorhanden':'nicht erkannt / prüfen'}</small></li>`;const have=Math.min(a.available||0,i.quantity),missing=Math.max(0,i.quantity-have);return `<li><span>${esc(text)}</span><small class="ingredient-stock ${missing<=0?'oktxt':''}">${missing<=0?'komplett da':`${formatQty(have,i.unit)} da · ${formatQty(missing,i.unit)} fehlen`}</small></li>`}
function recipeModal(r){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>${esc(r.title)}</h2><button class="close" data-close>×</button></div>${cover(r,true)}<div class="meta modal-meta"><span class="pill">${r.time||'–'} Min.</span><span class="pill">${r.servings||2} Portionen</span><span class="pill ok">${matchRecipe(r)}% vorhanden</span>${r.cookedCount?`<span class="pill">${r.cookedCount}× gekocht</span>`:''}</div>${r.source?.url?`<a class="source-link" href="${esc(r.source.url)}" target="_blank" rel="noopener">Original bei ${esc(r.source.name||'Quelle')} öffnen ↗</a>`:''}<div class="kpis"><div class="kpi"><b>${r.nutrition?.kcal||'–'}</b><span>kcal</span></div><div class="kpi"><b>${r.nutrition?.protein||'–'} g</b><span>Protein</span></div><div class="kpi"><b>${r.nutrition?.carbs||'–'} g</b><span>Kohlenhydrate</span></div></div><div class="section-title"><h2>Zutaten</h2><button data-action="recipeToShopping" data-id="${r.id}">+ Einkauf</button></div><ul class="ingredients">${r.ingredients.map(ingredientLine).join('')}</ul><div class="section-title"><h2>Zubereitung</h2></div><ol class="steps">${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${stars(r)}<div class="actions"><button class="secondary" data-action="cooked" data-id="${r.id}">✓ Heute gekocht</button><button class="secondary" data-action="favorite" data-id="${r.id}">${r.favorite?'★ Favorit':'☆ Favorit'}</button><button class="secondary" data-action="editRecipe" data-id="${r.id}">Bearbeiten</button></div></section></div>`}
function recipeForm(r={}){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>${r.id?'Rezept bearbeiten':'Neues Rezept'}</h2><button class="close" data-close>×</button></div><form id="recipeForm" data-id="${r.id||''}"><div class="field"><label>Name</label><input name="title" required value="${esc(r.title||'')}"></div><div class="field"><label>Rezeptbild</label>${r.image?`<img class="image-preview" src="${esc(safeUrl(r.image))}" alt="Rezeptbild">`:''}<input name="image" placeholder="Bild-URL (optional)" value="${esc(r.image?.startsWith('data:')?'':r.image||'')}"><label class="upload-btn">Foto vom iPhone auswählen<input id="recipeImageFile" type="file" accept="image/*" hidden></label><input type="hidden" name="imageData" value="${r.image?.startsWith('data:')?esc(r.image):''}"></div><div class="field"><label>Emoji / Symbol</label><input name="emoji" value="${esc(r.emoji||'🍽️')}"></div><div class="field"><label>Zeit in Minuten</label><input name="time" type="number" inputmode="numeric" value="${r.time||30}"></div><div class="field"><label>Portionen</label><input name="servings" type="number" inputmode="numeric" value="${r.servings||2}"></div><div class="field"><label>Zutaten – eine pro Zeile</label><textarea name="ingredients" required>${esc((r.ingredients||[]).join('\n'))}</textarea><small>Für den automatischen Vorratsabgleich am besten z. B. „500 ml Milch“, „1 kg Kartoffeln“ oder „2 Stück Paprika“ verwenden.</small></div><div class="field"><label>Zubereitung – ein Schritt pro Zeile</label><textarea name="steps" required>${esc((r.steps||[]).join('\n'))}</textarea></div><div class="field"><label>Tags – mit Komma trennen</label><input name="tags" value="${esc((r.tags||[]).join(', '))}"></div><div class="field"><label>Nährwerte pro Portion (optional)</label><div class="actions"><input name="kcal" type="number" placeholder="kcal" value="${r.nutrition?.kcal||''}"><input name="protein" type="number" placeholder="Protein g" value="${r.nutrition?.protein||''}"><input name="carbs" type="number" placeholder="KH g" value="${r.nutrition?.carbs||''}"></div></div><button class="primary full">Speichern</button>${r.id?`<div class="topgap"></div><button type="button" class="secondary danger full" data-action="deleteRecipe" data-id="${r.id}">Rezept löschen</button>`:''}</form></section></div>`}
function importModal(){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>Rezept importieren</h2><button class="close" data-close>×</button></div><form id="urlImportForm"><div class="field"><label>Chefkoch- oder Rezept-Link</label><input name="url" type="url" placeholder="https://www.chefkoch.de/rezepte/…" required></div><button class="primary full">Link automatisch einlesen</button><div id="importStatus" class="row-sub topgap"></div></form><div class="divider"><span>oder</span></div><form id="importForm"><div class="field"><label>Titel</label><input name="title" placeholder="z. B. Lasagne"></div><div class="field"><label>Rezepttext</label><textarea name="text" class="bigtext" placeholder="Zutaten:\n500 g ...\n...\n\nZubereitung:\n1. ..."></textarea></div><div class="field"><label>Bild-URL (optional)</label><input name="image" placeholder="https://…"></div><button class="secondary full">Text importieren</button></form></section></div>`}
function planModal(date,meal){const label=MEALS.find(x=>x[0]===meal)?.[1]||'Gericht';return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>${label} wählen</h2><button class="close" data-close>×</button></div><div class="list">${[...data.recipes].sort((a,b)=>scoreRecipe(b)-scoreRecipe(a)).map(r=>`<button class="row choice-row" data-plan-recipe="${r.id}" data-date="${date}" data-meal="${meal}">${r.image?`<img class="row-thumb" src="${esc(safeUrl(r.image))}" alt="">`:`<div class="choice-emoji">${r.emoji}</div>`}<div class="row-main"><div class="row-title">${esc(r.title)}</div><div class="row-sub">${r.time} Min. · ${matchRecipe(r)}% Vorrat</div></div></button>`).join('')}</div><div class="topgap"></div><button class="secondary danger full" data-plan-recipe="" data-date="${date}" data-meal="${meal}">Planung entfernen</button></section></div>`}
function pantryEditModal(p){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>Vorrat ändern</h2><button class="close" data-close>×</button></div><form id="pantryEditForm" data-id="${p.id}"><div class="field"><label>Lebensmittel</label><input name="name" value="${esc(p.name)}" required></div><div class="amount-edit"><input name="quantity" type="number" inputmode="decimal" min="0" step="0.01" value="${p.quantity}" required><select name="unit">${unitOptions(p.unit)}</select></div><button class="primary full topgap">Speichern</button></form></section></div>`}
function settingsModal(){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>Einstellungen</h2><button class="close" data-close>×</button></div><div class="row"><div class="row-main"><div class="row-title">Lernen & Empfehlungen</div><div class="row-sub">Bewertungen, Favoriten, Kochhistorie und Vorräte bleiben lokal auf deinem Gerät.</div></div></div><div class="section-title"><h2>Datensicherung</h2></div><div class="actions"><button class="secondary" data-action="export">Exportieren</button><label class="secondary import-label">Importieren<input id="backupFile" type="file" accept="application/json" hidden></label></div><div class="section-title"><h2>Installation auf dem iPhone</h2></div><div class="notice">In Safari öffnen → Teilen → „Zum Home-Bildschirm“. Danach startet MealMate wie eine normale App im Vollbild.</div></section></div>`}
function render(){const html=view==='home'?home():view==='discover'?discover():view==='recipes'?recipes():view==='plan'?plan():view==='shopping'?shopping():pantry();$('#app').innerHTML=`<div class="app">${html}${modal||''}${toast?`<div class="toast">${esc(toast)}</div>`:''}</div>`;bind()}

function addRequirement(name,quantity,unit,source='manuell'){
 name=String(name||'').trim();unit=normalizeUnit(unit);quantity=Number(quantity);if(!name||!unit||!(quantity>0))return null;
 const group=unitGroup(unit),inc=toBase(quantity,unit);
 let item=data.shopping.find(x=>nameMatches(x.name,name)&&unitGroup(x.unit)===group&&!x.done);
 if(!item){item={id:uid(),name,quantity:0,unit,done:false,requiredBase:0,availableBase:0,source};data.shopping.push(item)}
 item.requiredBase+=inc;item.unit=unit;item.availableBase=pantryBase(name,group);item.quantity=Math.max(0,fromBase(item.requiredBase-item.availableBase,unit));
 return {item,required:fromBase(item.requiredBase,unit),available:Math.min(fromBase(item.availableBase,unit),fromBase(item.requiredBase,unit)),missing:item.quantity}
}
function addIngredientRequirement(text,source){const ing=parseIngredient(text);if(ing.quantified)return addRequirement(ing.name,ing.quantity,ing.unit,source);return addRequirement(ing.name||text,1,'Stück',source)}
function refreshShoppingAgainstPantry(){data.shopping.filter(x=>!x.done).forEach(x=>{x.availableBase=pantryBase(x.name,unitGroup(x.unit));x.quantity=Math.max(0,fromBase(x.requiredBase-x.availableBase,x.unit))})}
function addRecipeIngredients(r,source=`Rezept: ${r.title}`){r.ingredients.forEach(i=>addIngredientRequirement(i,source))}
function addPlannedIngredients(){const totals=[];Object.values(data.planner).forEach(day=>MEALS.forEach(([meal])=>{const rid=day?.[meal],r=data.recipes.find(x=>x.id===rid);if(r)totals.push(r)}));totals.forEach(r=>addRecipeIngredients(r,`Wochenplan: ${r.title}`));return totals.length}
function addToPantry(name,quantity,unit){const group=unitGroup(unit),base=toBase(quantity,unit);let p=data.pantry.find(x=>nameMatches(x.name,name)&&unitGroup(x.unit)===group);if(p){const total=toBase(p.quantity,p.unit)+base;p.quantity=fromBase(total,p.unit)}else data.pantry.push({id:uid(),name,quantity:Number(quantity),unit:normalizeUnit(unit)});refreshShoppingAgainstPantry()}
function stockShoppingItem(id){const x=data.shopping.find(i=>i.id===id);if(!x||!x.done||x.quantity<=0)return;addToPantry(x.name,x.quantity,x.unit);data.shopping=data.shopping.filter(i=>i.id!==id);save()}

let planDrag=null,planDragMoved=false;
function planCell(el){return el?{date:el.dataset.plan,meal:el.dataset.meal}:null}
function movePlannedMeal(from,to){if(!from||!to||(from.date===to.date&&from.meal===to.meal))return false;data.planner[from.date]??=emptyMealPlan();data.planner[to.date]??=emptyMealPlan();const a=data.planner[from.date][from.meal]||null,b=data.planner[to.date][to.meal]||null;if(!a)return false;data.planner[to.date][to.meal]=a;data.planner[from.date][from.meal]=b;store.set(data);return true}
function clearPlanDropState(){$$('.meal-slot.drag-over').forEach(x=>x.classList.remove('drag-over'));$$('.meal-slot.dragging').forEach(x=>x.classList.remove('dragging'));document.body.classList.remove('plan-dragging')}
function bindPlanDragDrop(){
 const slots=$$('.meal-slot[data-plan]');
 slots.forEach(slot=>{
  if(slot.classList.contains('filled')){
   slot.ondragstart=e=>{planDrag=planCell(slot);planDragMoved=true;slot.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',`${planDrag.date}|${planDrag.meal}`)};
   slot.ondragend=()=>{planDrag=null;setTimeout(()=>planDragMoved=false,80);clearPlanDropState()};
  }
  slot.ondragover=e=>{if(!planDrag)return;e.preventDefault();e.dataTransfer.dropEffect='move';$$('.meal-slot.drag-over').forEach(x=>x.classList.remove('drag-over'));slot.classList.add('drag-over')};
  slot.ondrop=e=>{if(!planDrag)return;e.preventDefault();const from=planDrag,to=planCell(slot);planDrag=null;clearPlanDropState();if(movePlannedMeal(from,to)){planDragMoved=true;render();setTimeout(()=>planDragMoved=false,100)}};
 });
 $$('[data-drag-handle]').forEach(handle=>{
  handle.onpointerdown=e=>{if(e.pointerType==='mouse')return;e.preventDefault();e.stopPropagation();const source=handle.closest('.meal-slot');planDrag=planCell(source);planDragMoved=false;source.classList.add('dragging');document.body.classList.add('plan-dragging');handle.setPointerCapture?.(e.pointerId)};
  handle.onpointermove=e=>{if(!planDrag||e.pointerType==='mouse')return;e.preventDefault();planDragMoved=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('.meal-slot[data-plan]');$$('.meal-slot.drag-over').forEach(x=>x.classList.remove('drag-over'));if(target)target.classList.add('drag-over')};
  handle.onpointerup=e=>{if(!planDrag||e.pointerType==='mouse')return;e.preventDefault();const from=planDrag,target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('.meal-slot[data-plan]'),to=planCell(target);planDrag=null;clearPlanDropState();if(target&&movePlannedMeal(from,to)){render();flash('Gericht im Wochenplan verschoben.')}else{planDragMoved=false;render()}};
  handle.onpointercancel=()=>{planDrag=null;planDragMoved=false;clearPlanDropState()};
 });
}

function chefUrl(q){return `https://www.chefkoch.de/rs/s0/${encodeURIComponent(q)}/Rezepte.html`}
function normalizeProxy(v=''){try{const u=new URL(String(v).trim());if(u.protocol!=='https:')return '';return u.origin+u.pathname.replace(/\/$/,'')}catch{return ''}}
function chefProxyUrl(target){const base=normalizeProxy(CHEF_PROXY);if(!base)throw new Error('Cloudflare-Worker ist noch nicht eingerichtet.');return `${base}/proxy?url=${encodeURIComponent(target)}`}

async function loadChefFeed(q=chefQuery){
 chefQuery=(q||'Schnelle Gerichte').trim();chefLoading=true;chefError='';render();
 try{
  const target=chefUrl(chefQuery),proxy=chefProxyUrl(target);
  const res=await fetch(proxy,{headers:{Accept:'text/html'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);
  const html=await res.text(),doc=new DOMParser().parseFromString(html,'text/html'),items=[],seen=new Set();
  [...doc.querySelectorAll('a[href*="/rezepte/"]')].forEach(a=>{
   let href=a.getAttribute('href')||'';if(!href||href==='/rezepte/'||href.includes('/rezepte/suche'))return;
   try{href=new URL(href,'https://www.chefkoch.de').href}catch{return}
   if(!/chefkoch\.de\/rezepte\/\d+/i.test(href)||seen.has(href))return;
   const box=a.closest('article,li,[class*="recipe"],[class*="result"],[class*="card"]')||a.parentElement;
   const title=(a.querySelector('h2,h3,[class*="title"]')?.textContent||a.getAttribute('title')||a.textContent||'').replace(/\s+/g,' ').trim();
   if(title.length<3)return;
   const img=box?.querySelector('img')||a.querySelector('img');let image=img?.getAttribute('src')||img?.getAttribute('data-src')||img?.getAttribute('data-lazy-src')||'';
   try{if(image)image=new URL(image,'https://www.chefkoch.de').href}catch{image=''}
   const text=(box?.textContent||'').replace(/\s+/g,' ').trim(),tm=text.match(/\b\d+\s*Min\.?/i),rating=text.match(/\b\d(?:[,.]\d)?\s*\/\s*5/);
   seen.add(href);items.push({title:title.slice(0,150),url:href,image,meta:[tm?.[0],rating?.[0]].filter(Boolean).join(' · ')});
  });
  if(!items.length)throw new Error('Keine auslesbaren Rezeptkarten gefunden.');
  chefFeed=items.slice(0,30);chefLoading=false;render();
 }catch(err){chefFeed=[];chefLoading=false;chefError='Der Chefkoch-Feed konnte über deinen Worker nicht geladen werden. Prüfe in den Einstellungen die Worker-Adresse und teste sie erneut.';render()}
}
async function importChefToLibrary(url,planAfter=false){
 flash('Rezept wird von Chefkoch eingelesen …');
 try{
  let r=data.recipes.find(x=>x.source?.url===url);
  if(!r){r=await fetchRecipe(url);data.recipes.unshift(r);store.set(data)}
  if(planAfter){modal=chefPlanModal(r);render()}else{r.favorite=true;store.set(data);flash(`${r.title} wurde gemerkt.`)}
 }catch(err){window.open(url,'_blank','noopener');flash('Automatischer Import war nicht möglich – Chefkoch wurde geöffnet.')}
}
function chefPlanModal(r){const days=[0,1,2,3,4,5,6].map(addDays);return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>${esc(r.title)} planen</h2><button class="close" data-close>×</button></div><p class="row-sub">Wähle Tag und Mahlzeit.</p><div class="chef-plan-grid">${days.map(d=>{const k=dateKey(d);return `<div class="chef-plan-day"><b>${d.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'})}</b>${MEALS.map(([meal,label])=>`<button class="secondary" data-chef-slot="${k}|${meal}|${r.id}">${label}</button>`).join('')}</div>`}).join('')}</div></section></div>`}

function jsonLdRecipe(doc){const scripts=[...doc.querySelectorAll('script[type="application/ld+json"]')];for(const s of scripts){try{const raw=JSON.parse(s.textContent),arr=Array.isArray(raw)?raw:(raw['@graph']||[raw]),r=arr.find(x=>{const t=x?.['@type'];return t==='Recipe'||(Array.isArray(t)&&t.includes('Recipe'))});if(r)return r}catch{}}return null}
function durationMinutes(v){if(!v)return 30;const h=+(v.match(/(\d+)H/)?.[1]||0),m=+(v.match(/(\d+)M/)?.[1]||0);return h*60+m||30}
function instructionText(x){if(Array.isArray(x))return x.flatMap(i=>i.itemListElement?instructionText(i.itemListElement):(typeof i==='string'?[i]:[i.text||i.name].filter(Boolean)));if(typeof x==='string')return [x];return []}
async function fetchRecipe(url){
 const isChef=(()=>{try{return /(^|\.)chefkoch\.de$/i.test(new URL(url).hostname)}catch{return false}})();
 const urls=isChef?[chefProxyUrl(url)]:[url];let last;
 for(const u of urls){try{const res=await fetch(u,{headers:{Accept:'text/html'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const html=await res.text(),doc=new DOMParser().parseFromString(html,'text/html'),r=jsonLdRecipe(doc);if(!r)throw new Error('Keine strukturierten Rezeptdaten gefunden');const image=Array.isArray(r.image)?(typeof r.image[0]==='string'?r.image[0]:r.image[0]?.url):(typeof r.image==='object'?r.image?.url:r.image)||'';return {id:uid(),title:r.name||'Importiertes Rezept',emoji:'🍽️',image,time:durationMinutes(r.totalTime||r.prepTime),servings:parseInt(String(r.recipeYield||'2'))||2,tags:[...(Array.isArray(r.recipeCategory)?r.recipeCategory:[r.recipeCategory]).filter(Boolean),'Importiert'],ingredients:r.recipeIngredient||[],steps:instructionText(r.recipeInstructions),nutrition:{kcal:parseInt(r.nutrition?.calories)||null,protein:parseInt(r.nutrition?.proteinContent)||null,carbs:parseInt(r.nutrition?.carbohydrateContent)||null},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:{name:isChef?'Chefkoch':'Original',url}}}catch(e){last=e}}
 throw last||new Error('Import fehlgeschlagen')
}

function bind(){
 $$('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;modal=null;render()});
 $$('[data-recipe]').forEach(c=>c.onclick=()=>{const r=data.recipes.find(x=>x.id===c.dataset.recipe);modal=recipeModal(r);render()});
 $$('[data-close]').forEach(b=>b.onclick=()=>{modal=null;render()});
 $$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});
 const gs=$('#globalSearch');if(gs)gs.oninput=e=>{search=e.target.value;if(view==='home')view='recipes';render()};
 $$('[data-action]').forEach(b=>b.onclick=e=>action(b.dataset.action,b.dataset.id,e));
 $$('[data-check]').forEach(b=>b.onclick=()=>{const x=data.shopping.find(x=>x.id===b.dataset.check);x.done=!x.done;save()});
 $$('[data-del-shopping]').forEach(b=>b.onclick=()=>{data.shopping=data.shopping.filter(x=>x.id!==b.dataset.delShopping);save()});
 $$('[data-stock-shopping]').forEach(b=>b.onclick=()=>stockShoppingItem(b.dataset.stockShopping));
 $$('[data-del-pantry]').forEach(b=>b.onclick=()=>{data.pantry=data.pantry.filter(x=>x.id!==b.dataset.delPantry);refreshShoppingAgainstPantry();save()});
 $$('[data-edit-pantry]').forEach(b=>b.onclick=()=>{modal=pantryEditModal(data.pantry.find(x=>x.id===b.dataset.editPantry));render()});
 $$('[data-plan]').forEach(b=>{b.onclick=()=>{if(planDragMoved){planDragMoved=false;return}modal=planModal(b.dataset.plan,b.dataset.meal);render()};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();modal=planModal(b.dataset.plan,b.dataset.meal);render()}}});
 bindPlanDragDrop();
 $$('[data-plan-recipe]').forEach(b=>b.onclick=()=>{data.planner[b.dataset.date]??=emptyMealPlan();data.planner[b.dataset.date][b.dataset.meal]=b.dataset.planRecipe||null;modal=null;save()});
 $$('[data-rate]').forEach(b=>b.onclick=()=>{const r=data.recipes.find(x=>x.id===b.dataset.id);r.rating=+b.dataset.rate;data.taste.ratings=(data.taste.ratings||0)+1;modal=recipeModal(r);save()});
 $$('[data-chef]').forEach(b=>b.onclick=()=>window.open(chefUrl(b.dataset.chef),'_blank','noopener'));
 $$('[data-chef-feed]').forEach(b=>b.onclick=()=>loadChefFeed(b.dataset.chefFeed));
 $$('[data-chef-save]').forEach(b=>b.onclick=()=>importChefToLibrary(b.dataset.chefSave,false));
 $$('[data-chef-plan]').forEach(b=>b.onclick=()=>importChefToLibrary(b.dataset.chefPlan,true));
 $$('[data-chef-slot]').forEach(b=>b.onclick=()=>{const [k,meal,rid]=b.dataset.chefSlot.split('|');data.planner[k]??=emptyMealPlan();data.planner[k][meal]=rid;modal=null;save();flash('Gericht wurde in den Wochenplan eingetragen.')});
 const cfs=$('#chefFeedSearch');if(cfs)cfs.onsubmit=e=>{e.preventDefault();loadChefFeed(new FormData(cfs).get('q'))};
 if(view==='discover'&&normalizeProxy(CHEF_PROXY)&&!chefLoading&&!chefFeed.length&&!chefError)setTimeout(()=>loadChefFeed(chefQuery),0);
 const sf=$('#shoppingForm');if(sf)sf.onsubmit=e=>{e.preventDefault();const f=new FormData(sf),res=addRequirement(f.get('name'),f.get('quantity'),f.get('unit'));store.set(data);const msg=res?.missing>0?`${res.item.name}: ${formatQty(res.available,res.item.unit)} vorhanden – ${formatQty(res.missing,res.item.unit)} auf der Einkaufsliste.`:`${res?.item.name||'Artikel'} ist in ausreichender Menge vorhanden.`;flash(msg)};
 const pf=$('#pantryForm');if(pf)pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf);addToPantry(f.get('name'),f.get('quantity'),f.get('unit'));save()};
 const pe=$('#pantryEditForm');if(pe)pe.onsubmit=e=>{e.preventDefault();const f=new FormData(pe),p=data.pantry.find(x=>x.id===pe.dataset.id);p.name=f.get('name').trim();p.quantity=Number(f.get('quantity'))||0;p.unit=normalizeUnit(f.get('unit'));refreshShoppingAgainstPantry();modal=null;save()};
 const rf=$('#recipeForm');if(rf){const file=$('#recipeImageFile');if(file)file.onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{rf.elements.imageData.value=rd.result;const old=$('.image-preview');if(old)old.src=rd.result;else file.parentElement.insertAdjacentHTML('beforebegin',`<img class="image-preview" src="${rd.result}" alt="Rezeptbild">`)};rd.readAsDataURL(f)};rf.onsubmit=e=>{e.preventDefault();const f=new FormData(rf),id=rf.dataset.id||uid(),old=data.recipes.find(x=>x.id===id),image=f.get('imageData')||f.get('image')||old?.image||'';const rec={id,title:f.get('title').trim(),emoji:f.get('emoji')||'🍽️',image,time:+f.get('time')||30,servings:+f.get('servings')||2,ingredients:f.get('ingredients').split('\n').map(x=>x.trim()).filter(Boolean),steps:f.get('steps').split('\n').map(x=>x.trim()).filter(Boolean),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),nutrition:{kcal:+f.get('kcal')||null,protein:+f.get('protein')||null,carbs:+f.get('carbs')||null},favorite:old?.favorite||false,rating:old?.rating||0,cookedCount:old?.cookedCount||0,lastCooked:old?.lastCooked||null,source:old?.source||null};if(old)data.recipes=data.recipes.map(x=>x.id===id?rec:x);else data.recipes.unshift(rec);modal=null;save()}};
 const uif=$('#urlImportForm');if(uif)uif.onsubmit=async e=>{e.preventDefault();const url=new FormData(uif).get('url').trim(),st=$('#importStatus');st.textContent='Rezept wird eingelesen …';try{const r=await fetchRecipe(url);data.recipes.unshift(r);store.set(data);st.textContent='Import erfolgreich.';setTimeout(()=>{modal=recipeModal(r);view='recipes';render()},350)}catch(err){st.textContent='Automatischer Import nicht möglich: '+err.message}};
 const inf=$('#importForm');if(inf)inf.onsubmit=e=>{e.preventDefault();const f=new FormData(inf),raw=f.get('text').trim(),lines=raw.split('\n').map(x=>x.trim()).filter(Boolean);let split=lines.findIndex(x=>/zubereitung|anleitung|zubereiten/i.test(x));if(split<0)split=Math.max(1,Math.floor(lines.length*.45));const ing=lines.slice(0,split).filter(x=>!/zutaten/i.test(x)).map(x=>x.replace(/^[-•]\s*/,'')),steps=lines.slice(split+1).map(x=>x.replace(/^\d+[.)]\s*/,''));data.recipes.unshift({id:uid(),title:f.get('title').trim()||'Importiertes Rezept',emoji:'📥',image:f.get('image').trim(),time:30,servings:2,tags:['Importiert'],ingredients:ing,steps:steps.length?steps:['Zubereitung nach Originalrezept.'],nutrition:{},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:null});modal=null;view='recipes';save()};
 const bf=$('#backupFile');if(bf)bf.onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{data=migrate(JSON.parse(r.result));save()}catch{alert('Die Datei konnte nicht gelesen werden.')}};r.readAsText(file)};
}
function action(a,id){
 if(a==='addRecipe'){modal=recipeForm();render()}
 if(a==='editRecipe'){modal=recipeForm(data.recipes.find(x=>x.id===id));render()}
 if(a==='deleteRecipe'){data.recipes=data.recipes.filter(x=>x.id!==id);modal=null;save()}
 if(a==='importRecipe'){modal=importModal();render()}
 if(a==='settings'){modal=settingsModal();render()}
 if(a==='favorite'){const r=data.recipes.find(x=>x.id===id);r.favorite=!r.favorite;modal=recipeModal(r);save()}
 if(a==='cooked'){const r=data.recipes.find(x=>x.id===id);r.cookedCount=(r.cookedCount||0)+1;r.lastCooked=new Date().toISOString();modal=recipeModal(r);save()}
 if(a==='suggestWeek')suggestWeek();
 if(a==='chefSearch'){const q=$('#chefSearch')?.value.trim();if(q)window.open(chefUrl(q),'_blank','noopener')}
 if(a==='reloadChefFeed')loadChefFeed(chefQuery);
 if(a==='openChefSearch')window.open(chefUrl(chefQuery),'_blank','noopener');
 if(a==='clearDone'){data.shopping=data.shopping.filter(x=>!x.done);save()}
 if(a==='recipeToShopping'){const r=data.recipes.find(x=>x.id===id);addRecipeIngredients(r);store.set(data);modal=recipeModal(r);flash('Zutaten wurden mit deinem Vorrat abgeglichen.')}
 if(a==='planToShopping'){const count=addPlannedIngredients();store.set(data);view='shopping';flash(count?`${count} geplante Mahlzeiten wurden mit dem Vorrat abgeglichen.`:'Im Wochenplan sind noch keine Mahlzeiten eingetragen.')}
 if(a==='clearProxy'){data.settings.chefProxy='';chefFeed=[];chefError='';modal=settingsModal();save()}
 if(a==='export'){const blob=new Blob([JSON.stringify(data,null,null?0:2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='mealmate-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
