const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const uid=()=>Math.random().toString(36).slice(2,10);
const dateKey=d=>d.toISOString().slice(0,10);
const addDays=(n)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return d};
const seed={
 recipes:[
  {id:'r1',title:'Cremige Tomatenpasta',emoji:'🍝',image:'',time:25,servings:2,tags:['Vegetarisch','Schnell'],ingredients:['250 g Pasta','1 Dose gehackte Tomaten','1 Zwiebel','2 Knoblauchzehen','100 ml Sahne','Parmesan','Salz','Pfeffer'],steps:['Pasta al dente kochen.','Zwiebel und Knoblauch anschwitzen.','Tomaten und Sahne zugeben und 10 Minuten köcheln.','Pasta unterheben und mit Parmesan servieren.'],nutrition:{kcal:640,protein:21,carbs:91},favorite:true,rating:0,cookedCount:0,lastCooked:null,source:null},
  {id:'r2',title:'Kartoffel-Gemüse-Pfanne',emoji:'🥔',image:'',time:35,servings:2,tags:['Vegetarisch','Meal Prep'],ingredients:['500 g Kartoffeln','1 Paprika','1 Zucchini','1 Zwiebel','2 EL Öl','Paprikapulver','Salz','Pfeffer'],steps:['Kartoffeln würfeln und vorkochen.','Gemüse schneiden.','Alles in der Pfanne goldbraun braten und würzen.'],nutrition:{kcal:470,protein:10,carbs:68},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:null},
  {id:'r3',title:'Hähnchen-Reis-Bowl',emoji:'🍚',image:'',time:30,servings:2,tags:['Proteinreich'],ingredients:['300 g Hähnchenbrust','180 g Reis','1 Gurke','1 Karotte','2 EL Sojasauce','1 TL Honig'],steps:['Reis kochen.','Hähnchen anbraten und mit Sojasauce und Honig glasieren.','Gemüse schneiden und alles in Bowls anrichten.'],nutrition:{kcal:590,protein:43,carbs:72},favorite:true,rating:0,cookedCount:0,lastCooked:null,source:null},
  {id:'r4',title:'Pfannkuchen',emoji:'🥞',image:'',time:20,servings:2,tags:['Süß','Schnell'],ingredients:['200 g Mehl','2 Eier','350 ml Milch','1 Prise Salz','1 TL Vanilleextrakt','Öl zum Braten'],steps:['Zutaten zu einem glatten Teig verrühren.','10 Minuten ruhen lassen.','Portionsweise in wenig Öl ausbacken.'],nutrition:{kcal:520,protein:20,carbs:65},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:null}
 ],
 pantry:['Pasta','gehackte Tomaten','Zwiebel','Knoblauch','Kartoffeln','Salz','Pfeffer'],shopping:[{id:'s1',text:'Milch',done:false},{id:'s2',text:'Eier',done:false}],planner:{},settings:{name:'Felix'},taste:{ratings:0}
};
const clone=x=>JSON.parse(JSON.stringify(x));
const store={get(){try{const d=JSON.parse(localStorage.getItem('mealmate_data'));return migrate(d||clone(seed))}catch{return clone(seed)}},set(v){localStorage.setItem('mealmate_data',JSON.stringify(v))}};
function migrate(d){d.recipes=d.recipes||[];d.recipes.forEach(r=>{r.image??='';r.rating??=0;r.cookedCount??=0;r.lastCooked??=null;r.source??=null;r.tags??=[];r.ingredients??=[];r.steps??=[]});d.taste??={ratings:0};d.planner??={};d.pantry??=[];d.shopping??=[];return d}
let data=store.get(),view='home',filter='Alle',search='',modal=null;
function save(){store.set(data);render()}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function safeUrl(u=''){try{const x=new URL(u);return ['http:','https:','data:'].includes(x.protocol)?u:''}catch{return u.startsWith('data:image/')?u:''}}
function ingredientName(s){return s.toLowerCase().replace(/^\s*[\d.,/]+\s*(g|kg|ml|l|el|tl|stk|stück|dose|dosen)?\s*/i,'').replace(/\([^)]*\)/g,'').trim()}
function matchRecipe(r){if(!r.ingredients.length)return 0;const p=data.pantry.map(x=>x.toLowerCase());const hits=r.ingredients.filter(i=>p.some(x=>ingredientName(i).includes(x)||x.includes(ingredientName(i)))).length;return Math.round(hits/r.ingredients.length*100)}
function cover(r,detail=false){const u=safeUrl(r.image||'');return u?`<div class="${detail?'detail-cover':'recipe-cover'} has-image" style="background-image:url('${esc(u)}')"><span>${r.emoji||'🍽️'}</span></div>`:`<div class="${detail?'detail-cover':'recipe-cover'}"><span>${r.emoji||'🍽️'}</span></div>`}
function nav(){return `<nav class="nav">${[['home','⌂','Start'],['discover','✦','Entdecken'],['recipes','◫','Rezepte'],['plan','◷','Plan'],['shopping','✓','Einkauf'],['pantry','◉','Vorrat']].map(([v,i,l])=>`<button data-nav="${v}" class="${view===v?'active':''}"><span class="ico">${i}</span>${l}</button>`).join('')}</nav>`}
function header(title='MealMate',sub='Deine private Koch-App'){return `<header class="top"><div class="brandrow"><div><div class="brand">${title}</div><div class="sub">${sub}</div></div><button class="iconbtn" data-action="settings">⚙︎</button></div></header>`}
function recipeCard(r){const m=matchRecipe(r);return `<article class="card" data-recipe="${r.id}">${cover(r)}<div class="recipe-body"><div class="recipe-title">${esc(r.title)}</div><div class="meta"><span class="pill">${r.time||'–'} Min.</span><span class="pill ${m>=60?'ok':''}">${m}% da</span>${r.rating?`<span class="pill">★ ${r.rating}/5</span>`:''}</div></div></article>`}
function preferenceSummary(){const rated=data.recipes.filter(r=>r.rating>0);if(!rated.length)return 'Bewerte Gerichte nach dem Kochen – daraus lernt MealMate deinen Geschmack.';const tags={};rated.forEach(r=>r.tags.forEach(t=>tags[t]=(tags[t]||0)+(r.rating-3)));const top=Object.entries(tags).sort((a,b)=>b[1]-a[1]).filter(x=>x[1]>0).slice(0,2).map(x=>x[0]);return top.length?`Du magst bisher besonders: ${top.join(' · ')}.`:'MealMate lernt weiter aus deinen Bewertungen, Favoriten und gekochten Gerichten.'}
function scoreRecipe(r,used=[]){let s=matchRecipe(r)*.035+(r.favorite?2.2:0)+(r.rating||0)*1.5+Math.min(r.cookedCount||0,3)*.15;const tagAffinity={};data.recipes.filter(x=>x.rating).forEach(x=>x.tags.forEach(t=>tagAffinity[t]=(tagAffinity[t]||0)+(x.rating-3)));r.tags.forEach(t=>s+=(tagAffinity[t]||0)*.35);if(r.time<=30)s+=.4;if(r.lastCooked){const days=(Date.now()-new Date(r.lastCooked))/86400000;if(days<5)s-=4;else if(days<10)s-=1.5}if(used.some(x=>x.tags.some(t=>r.tags.includes(t))))s-=.7;s+=Math.random()*.15;return s}
function suggestWeek(){const chosen=[];for(let i=0;i<7;i++){const candidates=data.recipes.filter(r=>!chosen.includes(r));if(!candidates.length)break;candidates.sort((a,b)=>scoreRecipe(b,chosen)-scoreRecipe(a,chosen));chosen.push(candidates[0]);data.planner[dateKey(addDays(i))]=candidates[0].id}save()}
function home(){const possible=[...data.recipes].sort((a,b)=>scoreRecipe(b)-scoreRecipe(a)).slice(0,4);return `${header()}<main class="content"><section class="hero"><h1>Was kann ich essen?</h1><p>Ich gleiche Vorräte und Geschmack ab und werde mit jeder Bewertung persönlicher.</p></section><div class="learn-card"><b>MealMate lernt mit</b><span>${esc(preferenceSummary())}</span></div><div class="search"><input id="globalSearch" placeholder="Rezepte durchsuchen…" value="${esc(search)}"></div><div class="section-title"><h2>Für dich empfohlen</h2><button data-action="suggestWeek">Woche planen</button></div><div class="grid">${possible.map(recipeCard).join('')}</div><div class="section-title"><h2>Favoriten</h2><button data-nav="recipes">Alle</button></div><div class="grid">${data.recipes.filter(r=>r.favorite).slice(0,3).map(recipeCard).join('')||'<div class="empty">Noch keine Favoriten.</div>'}</div></main><button class="fab" data-action="addRecipe">+</button>${nav()}`}
function discover(){const qs=['Lasagne','Schnelle Gerichte','Hähnchen','Pasta','Kartoffeln','Vegetarisch','Auflauf','Pfannkuchen'];return `${header('Entdecken','Chefkoch & deine persönlichen Empfehlungen')}<main class="content"><section class="hero discover-hero"><h1>Neue Rezepte finden</h1><p>Suche bei Chefkoch und importiere interessante Rezepte anschließend mit Bild in MealMate.</p></section><div class="section-title"><h2>Chefkoch durchsuchen</h2></div><div class="search"><input id="chefSearch" placeholder="z. B. Lasagne, Hähnchen, schnell…"><button class="primary" data-action="chefSearch">Suchen</button></div><div class="chips" style="flex-wrap:wrap;overflow:visible">${qs.map(q=>`<button class="chip" data-chef="${esc(q)}">${esc(q)}</button>`).join('')}</div><div class="notice">Chefkoch öffnet sich in einem neuen Tab. Danach kannst du den Rezept-Link über „Importieren“ in MealMate übernehmen. Wenn die Seite strukturierte Rezeptdaten bereitstellt, übernimmt MealMate Titel, Bild, Zutaten und Schritte automatisch; sonst bleibt der manuelle Import.</div><div class="section-title"><h2>Für dich</h2><button data-action="suggestWeek">Wochenplan vorschlagen</button></div><div class="grid">${[...data.recipes].sort((a,b)=>scoreRecipe(b)-scoreRecipe(a)).slice(0,6).map(recipeCard).join('')}</div><button class="primary" style="width:100%;margin-top:18px" data-action="importRecipe">Rezept-Link importieren</button></main>${nav()}`}
function recipes(){const tags=['Alle','Favoriten','Schnell','Vegetarisch','Proteinreich','Meal Prep'];const list=data.recipes.filter(r=>{const q=search.toLowerCase(),qok=!q||r.title.toLowerCase().includes(q)||r.ingredients.join(' ').toLowerCase().includes(q),fok=filter==='Alle'||(filter==='Favoriten'?r.favorite:r.tags.includes(filter));return qok&&fok});return `${header('Rezepte',`${data.recipes.length} gespeichert`)}<main class="content"><div class="search"><input id="globalSearch" placeholder="Suche nach Rezept oder Zutat…" value="${esc(search)}"></div><div class="chips">${tags.map(t=>`<button class="chip ${filter===t?'active':''}" data-filter="${t}">${t}</button>`).join('')}</div><div class="section-title"><h2>Deine Rezepte</h2><button data-action="importRecipe">Importieren</button></div><div class="grid">${list.map(recipeCard).join('')||'<div class="empty">Keine Treffer.</div>'}</div></main><button class="fab" data-action="addRecipe">+</button>${nav()}`}
function plan(){const days=[0,1,2,3,4,5,6].map(addDays);return `${header('Wochenplan','MealMate kann die Woche für dich zusammenstellen')}<main class="content"><button class="primary suggest" data-action="suggestWeek">✦ Wochenplan automatisch vorschlagen</button><div class="learn-card"><b>So wird ausgewählt</b><span>Bewertungen, Favoriten, Vorräte, Kochhistorie, Zubereitungszeit und etwas Abwechslung fließen in die Vorschläge ein.</span></div><div class="list">${days.map(d=>{const k=dateKey(d),rid=data.planner[k],r=data.recipes.find(x=>x.id===rid);return `<div class="row"><div class="row-main"><div class="row-title">${d.toLocaleDateString('de-DE',{weekday:'long'})}</div><div class="row-sub">${d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'})}</div>${r?`<div class="planned-mini">${r.image?`<img src="${esc(safeUrl(r.image))}" alt="">`:`<span>${r.emoji}</span>`}<b>${esc(r.title)}</b></div>`:''}</div><button class="secondary" data-plan="${k}">${r?'Ändern':'+ Planen'}</button></div>`}).join('')}</div><div class="section-title"><h2>Einkauf automatisch ergänzen</h2></div><button class="primary" style="width:100%" data-action="planToShopping">Zutaten aus dem Wochenplan hinzufügen</button></main>${nav()}`}
function shopping(){return `${header('Einkaufsliste','Alles lokal auf deinem iPhone')}<main class="content"><div class="search"><input id="newShopping" placeholder="Artikel hinzufügen…"><button class="primary" data-action="addShopping">+</button></div><div class="list">${data.shopping.map(x=>`<div class="row"><button class="check ${x.done?'done':''}" data-check="${x.id}">${x.done?'✓':''}</button><div class="row-main"><div class="row-title" style="${x.done?'text-decoration:line-through;color:#929792':''}">${esc(x.text)}</div></div><button class="iconbtn mini" data-del-shopping="${x.id}">×</button></div>`).join('')||'<div class="empty">Deine Liste ist leer.</div>'}</div>${data.shopping.length?'<div style="height:12px"></div><button class="secondary danger" style="width:100%" data-action="clearDone">Erledigte löschen</button>':''}</main>${nav()}`}
function pantry(){return `${header('Vorrat','Damit MealMate weiß, was da ist')}<main class="content"><div class="search"><input id="newPantry" placeholder="Zutat hinzufügen…"><button class="primary" data-action="addPantry">+</button></div><div class="chips" style="flex-wrap:wrap;overflow:visible">${data.pantry.map((p,i)=>`<button class="chip" data-del-pantry="${i}">${esc(p)} ×</button>`).join('')}</div><div class="section-title"><h2>Beste Treffer</h2></div><div class="grid">${[...data.recipes].sort((a,b)=>matchRecipe(b)-matchRecipe(a)).map(recipeCard).join('')}</div></main>${nav()}`}
function stars(r){return `<div class="rating"><span>Wie hat es dir geschmeckt?</span><div>${[1,2,3,4,5].map(n=>`<button data-rate="${n}" data-id="${r.id}" class="${r.rating>=n?'on':''}">★</button>`).join('')}</div><small>${r.rating?`Deine Bewertung: ${r.rating}/5`:'Deine Bewertung verbessert künftige Vorschläge.'}</small></div>`}
function recipeModal(r){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>${esc(r.title)}</h2><button class="close" data-close>×</button></div>${cover(r,true)}<div class="meta" style="margin:14px 0"><span class="pill">${r.time||'–'} Min.</span><span class="pill">${r.servings||2} Portionen</span><span class="pill ok">${matchRecipe(r)}% vorhanden</span>${r.cookedCount?`<span class="pill">${r.cookedCount}× gekocht</span>`:''}</div>${r.source?.url?`<a class="source-link" href="${esc(r.source.url)}" target="_blank" rel="noopener">Original bei ${esc(r.source.name||'Quelle')} öffnen ↗</a>`:''}<div class="kpis"><div class="kpi"><b>${r.nutrition?.kcal||'–'}</b><span>kcal</span></div><div class="kpi"><b>${r.nutrition?.protein||'–'} g</b><span>Protein</span></div><div class="kpi"><b>${r.nutrition?.carbs||'–'} g</b><span>Kohlenhydrate</span></div></div><div class="section-title"><h2>Zutaten</h2><button data-action="recipeToShopping" data-id="${r.id}">+ Einkauf</button></div><ul class="ingredients">${r.ingredients.map(i=>`<li><span>${esc(i)}</span></li>`).join('')}</ul><div class="section-title"><h2>Zubereitung</h2></div><ol class="steps">${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${stars(r)}<div class="actions"><button class="secondary" data-action="cooked" data-id="${r.id}">✓ Heute gekocht</button><button class="secondary" data-action="favorite" data-id="${r.id}">${r.favorite?'★ Favorit':'☆ Favorit'}</button><button class="secondary" data-action="editRecipe" data-id="${r.id}">Bearbeiten</button></div></section></div>`}
function recipeForm(r={}){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>${r.id?'Rezept bearbeiten':'Neues Rezept'}</h2><button class="close" data-close>×</button></div><form id="recipeForm" data-id="${r.id||''}"><div class="field"><label>Name</label><input name="title" required value="${esc(r.title||'')}"></div><div class="field"><label>Rezeptbild</label>${r.image?`<img class="image-preview" src="${esc(safeUrl(r.image))}" alt="Rezeptbild">`:''}<input name="image" placeholder="Bild-URL (optional)" value="${esc(r.image?.startsWith('data:')?'':r.image||'')}"><label class="upload-btn">Foto vom iPhone auswählen<input id="recipeImageFile" type="file" accept="image/*" hidden></label><input type="hidden" name="imageData" value="${r.image?.startsWith('data:')?esc(r.image):''}"></div><div class="field"><label>Emoji / Symbol</label><input name="emoji" value="${esc(r.emoji||'🍽️')}"></div><div class="field"><label>Zeit in Minuten</label><input name="time" type="number" inputmode="numeric" value="${r.time||30}"></div><div class="field"><label>Portionen</label><input name="servings" type="number" inputmode="numeric" value="${r.servings||2}"></div><div class="field"><label>Zutaten – eine pro Zeile</label><textarea name="ingredients" required>${esc((r.ingredients||[]).join('\n'))}</textarea></div><div class="field"><label>Zubereitung – ein Schritt pro Zeile</label><textarea name="steps" required>${esc((r.steps||[]).join('\n'))}</textarea></div><div class="field"><label>Tags – mit Komma trennen</label><input name="tags" value="${esc((r.tags||[]).join(', '))}"></div><div class="field"><label>Nährwerte pro Portion (optional)</label><div class="actions"><input name="kcal" type="number" placeholder="kcal" value="${r.nutrition?.kcal||''}"><input name="protein" type="number" placeholder="Protein g" value="${r.nutrition?.protein||''}"><input name="carbs" type="number" placeholder="KH g" value="${r.nutrition?.carbs||''}"></div></div><button class="primary" style="width:100%">Speichern</button>${r.id?`<div style="height:10px"></div><button type="button" class="secondary danger" style="width:100%" data-action="deleteRecipe" data-id="${r.id}">Rezept löschen</button>`:''}</form></section></div>`}
function importModal(){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>Rezept importieren</h2><button class="close" data-close>×</button></div><form id="urlImportForm"><div class="field"><label>Chefkoch- oder Rezept-Link</label><input name="url" type="url" placeholder="https://www.chefkoch.de/rezepte/…" required></div><button class="primary" style="width:100%">Link automatisch einlesen</button><div id="importStatus" class="row-sub" style="margin-top:8px"></div></form><div class="divider"><span>oder</span></div><form id="importForm"><div class="field"><label>Titel</label><input name="title" placeholder="z. B. Lasagne"></div><div class="field"><label>Rezepttext</label><textarea name="text" style="min-height:180px" placeholder="Zutaten:\n500 g ...\n...\n\nZubereitung:\n1. ..."></textarea></div><div class="field"><label>Bild-URL (optional)</label><input name="image" placeholder="https://…"></div><button class="secondary" style="width:100%">Text importieren</button></form><div class="notice">Automatisches Einlesen funktioniert, wenn die Rezeptseite strukturierte Daten liefert und Browserzugriff zulässt. Falls Chefkoch den direkten Abruf blockiert, kannst du Titel/Text/Bild weiterhin manuell übernehmen.</div></section></div>`}
function planModal(date){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>Gericht wählen</h2><button class="close" data-close>×</button></div><div class="list">${[...data.recipes].sort((a,b)=>scoreRecipe(b)-scoreRecipe(a)).map(r=>`<button class="row" style="text-align:left" data-plan-recipe="${r.id}" data-date="${date}">${r.image?`<img class="row-thumb" src="${esc(safeUrl(r.image))}" alt="">`:`<div style="font-size:30px">${r.emoji}</div>`}<div class="row-main"><div class="row-title">${esc(r.title)}</div><div class="row-sub">${r.time} Min. · Empfehlung ${Math.round(scoreRecipe(r)*10)/10}</div></div></button>`).join('')}</div><div style="height:10px"></div><button class="secondary danger" style="width:100%" data-plan-recipe="" data-date="${date}">Planung entfernen</button></section></div>`}
function settingsModal(){return `<div class="modal-back"><section class="modal"><div class="modal-head"><h2>Einstellungen</h2><button class="close" data-close>×</button></div><div class="row"><div class="row-main"><div class="row-title">Lernen & Empfehlungen</div><div class="row-sub">Die Lernlogik läuft lokal. Bewertungen, Favoriten, Kochhistorie und Vorräte verlassen dein Gerät nicht.</div></div></div><div class="section-title"><h2>Datensicherung</h2></div><div class="actions"><button class="secondary" data-action="export">Exportieren</button><label class="secondary" style="text-align:center;cursor:pointer">Importieren<input id="backupFile" type="file" accept="application/json" hidden></label></div><div class="section-title"><h2>Installation auf dem iPhone</h2></div><div class="notice">In Safari öffnen → Teilen → „Zum Home-Bildschirm“. Danach startet MealMate wie eine normale App im Vollbild.</div></section></div>`}
function render(){let html=view==='home'?home():view==='discover'?discover():view==='recipes'?recipes():view==='plan'?plan():view==='shopping'?shopping():pantry();$('#app').innerHTML=`<div class="app">${html}${modal||''}</div>`;bind()}
function chefUrl(q){return `https://www.chefkoch.de/rs/s0/${encodeURIComponent(q)}/Rezepte.html`}
function jsonLdRecipe(doc){const scripts=[...doc.querySelectorAll('script[type="application/ld+json"]')];for(const s of scripts){try{const raw=JSON.parse(s.textContent);const arr=Array.isArray(raw)?raw:(raw['@graph']||[raw]);const r=arr.find(x=>{const t=x?.['@type'];return t==='Recipe'||(Array.isArray(t)&&t.includes('Recipe'))});if(r)return r}catch{}}return null}
function durationMinutes(v){if(!v)return 30;const h=+(v.match(/(\d+)H/)?.[1]||0),m=+(v.match(/(\d+)M/)?.[1]||0);return h*60+m||30}
function instructionText(x){if(Array.isArray(x))return x.flatMap(i=>i.itemListElement?instructionText(i.itemListElement):(typeof i==='string'?[i]:[i.text||i.name].filter(Boolean)));if(typeof x==='string')return [x];return []}
async function fetchRecipe(url){const urls=[url,`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`];let last;for(const u of urls){try{const res=await fetch(u,{headers:{'Accept':'text/html'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const html=await res.text();const doc=new DOMParser().parseFromString(html,'text/html');const r=jsonLdRecipe(doc);if(!r)throw new Error('Keine strukturierten Rezeptdaten gefunden');const image=Array.isArray(r.image)?(typeof r.image[0]==='string'?r.image[0]:r.image[0]?.url):(typeof r.image==='object'?r.image?.url:r.image)||'';return {id:uid(),title:r.name||'Importiertes Rezept',emoji:'🍽️',image,time:durationMinutes(r.totalTime||r.prepTime),servings:parseInt(String(r.recipeYield||'2'))||2,tags:[...(Array.isArray(r.recipeCategory)?r.recipeCategory:[r.recipeCategory]).filter(Boolean),'Importiert'],ingredients:r.recipeIngredient||[],steps:instructionText(r.recipeInstructions),nutrition:{kcal:parseInt(r.nutrition?.calories)||null,protein:parseInt(r.nutrition?.proteinContent)||null,carbs:parseInt(r.nutrition?.carbohydrateContent)||null},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:{name:new URL(url).hostname.includes('chefkoch')?'Chefkoch':'Original',url}}}catch(e){last=e}}throw last||new Error('Import fehlgeschlagen')}
function bind(){
 $$('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;modal=null;render()});$$('[data-recipe]').forEach(c=>c.onclick=()=>{const r=data.recipes.find(x=>x.id===c.dataset.recipe);modal=recipeModal(r);render()});$$('[data-close]').forEach(b=>b.onclick=()=>{modal=null;render()});$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});
 const gs=$('#globalSearch');if(gs)gs.oninput=e=>{search=e.target.value;if(view==='home')view='recipes';render()};$$('[data-action]').forEach(b=>b.onclick=e=>action(b.dataset.action,b.dataset.id,e));$$('[data-check]').forEach(b=>b.onclick=()=>{const x=data.shopping.find(x=>x.id===b.dataset.check);x.done=!x.done;save()});$$('[data-del-shopping]').forEach(b=>b.onclick=()=>{data.shopping=data.shopping.filter(x=>x.id!==b.dataset.delShopping);save()});$$('[data-del-pantry]').forEach(b=>b.onclick=()=>{data.pantry.splice(+b.dataset.delPantry,1);save()});$$('[data-plan]').forEach(b=>b.onclick=()=>{modal=planModal(b.dataset.plan);render()});$$('[data-plan-recipe]').forEach(b=>b.onclick=()=>{if(b.dataset.planRecipe)data.planner[b.dataset.date]=b.dataset.planRecipe;else delete data.planner[b.dataset.date];modal=null;save()});$$('[data-rate]').forEach(b=>b.onclick=()=>{const r=data.recipes.find(x=>x.id===b.dataset.id);r.rating=+b.dataset.rate;data.taste.ratings=(data.taste.ratings||0)+1;modal=recipeModal(r);save()});$$('[data-chef]').forEach(b=>b.onclick=()=>window.open(chefUrl(b.dataset.chef),'_blank','noopener'));
 const rf=$('#recipeForm');if(rf){const file=$('#recipeImageFile');if(file)file.onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{rf.elements.imageData.value=rd.result;const old=$('.image-preview');if(old)old.src=rd.result;else file.parentElement.insertAdjacentHTML('beforebegin',`<img class="image-preview" src="${rd.result}" alt="Rezeptbild">`)};rd.readAsDataURL(f)};rf.onsubmit=e=>{e.preventDefault();const f=new FormData(rf),id=rf.dataset.id||uid(),old=data.recipes.find(x=>x.id===id),image=f.get('imageData')||f.get('image')||old?.image||'';const rec={id,title:f.get('title').trim(),emoji:f.get('emoji')||'🍽️',image,time:+f.get('time')||30,servings:+f.get('servings')||2,ingredients:f.get('ingredients').split('\n').map(x=>x.trim()).filter(Boolean),steps:f.get('steps').split('\n').map(x=>x.trim()).filter(Boolean),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),nutrition:{kcal:+f.get('kcal')||null,protein:+f.get('protein')||null,carbs:+f.get('carbs')||null},favorite:old?.favorite||false,rating:old?.rating||0,cookedCount:old?.cookedCount||0,lastCooked:old?.lastCooked||null,source:old?.source||null};if(old)data.recipes=data.recipes.map(x=>x.id===id?rec:x);else data.recipes.unshift(rec);modal=null;save()}}
 const uif=$('#urlImportForm');if(uif)uif.onsubmit=async e=>{e.preventDefault();const url=new FormData(uif).get('url').trim(),st=$('#importStatus');st.textContent='Rezept wird eingelesen …';try{const r=await fetchRecipe(url);data.recipes.unshift(r);store.set(data);st.textContent='Import erfolgreich.';setTimeout(()=>{modal=recipeModal(r);view='recipes';render()},350)}catch(err){st.textContent='Automatischer Import nicht möglich: '+err.message}};
 const inf=$('#importForm');if(inf)inf.onsubmit=e=>{e.preventDefault();const f=new FormData(inf),raw=f.get('text').trim(),lines=raw.split('\n').map(x=>x.trim()).filter(Boolean);let split=lines.findIndex(x=>/zubereitung|anleitung|zubereiten/i.test(x));if(split<0)split=Math.max(1,Math.floor(lines.length*.45));const ing=lines.slice(0,split).filter(x=>!/zutaten/i.test(x)).map(x=>x.replace(/^[-•]\s*/,'')),steps=lines.slice(split+1).map(x=>x.replace(/^\d+[.)]\s*/,''));data.recipes.unshift({id:uid(),title:f.get('title').trim()||'Importiertes Rezept',emoji:'📥',image:f.get('image').trim(),time:30,servings:2,tags:['Importiert'],ingredients:ing,steps:steps.length?steps:['Zubereitung nach Originalrezept.'],nutrition:{},favorite:false,rating:0,cookedCount:0,lastCooked:null,source:null});modal=null;view='recipes';save()};
 const bf=$('#backupFile');if(bf)bf.onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{data=migrate(JSON.parse(r.result));save()}catch{alert('Die Datei konnte nicht gelesen werden.')}};r.readAsText(file)}
}
function action(a,id){
 if(a==='addRecipe'){modal=recipeForm();render()}if(a==='editRecipe'){modal=recipeForm(data.recipes.find(x=>x.id===id));render()}if(a==='deleteRecipe'){data.recipes=data.recipes.filter(x=>x.id!==id);modal=null;save()}if(a==='importRecipe'){modal=importModal();render()}if(a==='settings'){modal=settingsModal();render()}if(a==='favorite'){const r=data.recipes.find(x=>x.id===id);r.favorite=!r.favorite;modal=recipeModal(r);save()}if(a==='cooked'){const r=data.recipes.find(x=>x.id===id);r.cookedCount=(r.cookedCount||0)+1;r.lastCooked=new Date().toISOString();modal=recipeModal(r);save()}if(a==='suggestWeek'){suggestWeek()}if(a==='chefSearch'){const q=$('#chefSearch')?.value.trim();if(q)window.open(chefUrl(q),'_blank','noopener')}if(a==='addShopping'){const i=$('#newShopping');if(i?.value.trim()){data.shopping.push({id:uid(),text:i.value.trim(),done:false});save()}}if(a==='clearDone'){data.shopping=data.shopping.filter(x=>!x.done);save()}if(a==='addPantry'){const i=$('#newPantry');if(i?.value.trim()&&!data.pantry.some(x=>x.toLowerCase()===i.value.trim().toLowerCase())){data.pantry.push(i.value.trim());save()}}if(a==='recipeToShopping'){const r=data.recipes.find(x=>x.id===id);r.ingredients.forEach(text=>{if(!data.shopping.some(x=>x.text===text))data.shopping.push({id:uid(),text,done:false})});save();modal=recipeModal(r);render()}if(a==='planToShopping'){Object.values(data.planner).forEach(rid=>{const r=data.recipes.find(x=>x.id===rid);r?.ingredients.forEach(text=>{if(!data.shopping.some(x=>x.text===text))data.shopping.push({id:uid(),text,done:false})})});view='shopping';save()}if(a==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='mealmate-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),500)}}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
